version: "3.9"
services:
  frontend:
    build:
      context: ./front-rent
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    container_name: frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./back-rent
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
